<a href="https://colab.research.google.com/github/mayankp158/Michigan-University-ML-/blob/main/python_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import csv
%precision 2
with open('mpg.csv') as new:
  mpg = list(csv.DictReader(new))

mpg[:3]

[OrderedDict([('mpg', '18'),
              ('cylinders', '8'),
              ('displacement', '307'),
              ('horsepower', '130'),
              ('weight', '3504'),
              ('acceleration', '12'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'chevrolet chevelle malibu')]),
 OrderedDict([('mpg', '15'),
              ('cylinders', '8'),
              ('displacement', '350'),
              ('horsepower', '165'),
              ('weight', '3693'),
              ('acceleration', '11.5'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'buick skylark 320')]),
 OrderedDict([('mpg', '18'),
              ('cylinders', '8'),
              ('displacement', '318'),
              ('horsepower', '150'),
              ('weight', '3436'),
              ('acceleration', '11'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'plymouth satellite')])]

In [ ]:
len(mpg)

398

In [ ]:
mpg[0].keys()

odict_keys(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'name'])

In [ ]:
sum(float(i['weight']) for i in mpg)/len(mpg)

2970.42

In [ ]:
cyl = set(j['cylinders'] for j in mpg)
cyl

{'3', '4', '5', '6', '8'}

In [ ]:
ctympgbycl = []
for i in cyl:
  sum1 = 0
  count1 = 0
  for j in mpg:
    if j['cylinders'] == i:
      sum1 += float(j['cylinders'])
      count1 += 1
  ctympgbycl.append((i,sum1/count1))

ctympgbycl.sort(key=lambda x: x[0])
ctympgbycl

[('3', 3.00), ('4', 4.00), ('5', 5.00), ('6', 6.00), ('8', 8.00)]

In [ ]:
vc = set(j['name'] for j in mpg)
vc

{'amc ambassador brougham',
 'amc ambassador dpl',
 'amc ambassador sst',
 'amc concord',
 'amc concord d/l',
 'amc concord dl',
 'amc concord dl 6',
 'amc gremlin',
 'amc hornet',
 'amc hornet sportabout (sw)',
 'amc matador',
 'amc matador (sw)',
 'amc pacer',
 'amc pacer d/l',
 'amc rebel sst',
 'amc spirit dl',
 'audi 100 ls',
 'audi 100ls',
 'audi 4000',
 'audi 5000',
 'audi 5000s (diesel)',
 'audi fox',
 'bmw 2002',
 'bmw 320i',
 'buick century',
 'buick century 350',
 'buick century limited',
 'buick century luxus (sw)',
 'buick century special',
 'buick electra 225 custom',
 'buick estate wagon (sw)',
 'buick lesabre custom',
 'buick opel isuzu deluxe',
 'buick regal sport coupe (turbo)',
 'buick skyhawk',
 'buick skylark',
 'buick skylark 320',
 'buick skylark limited',
 'cadillac eldorado',
 'cadillac seville',
 'capri ii',
 'chevroelt chevelle malibu',
 'chevrolet bel air',
 'chevrolet camaro',
 'chevrolet caprice classic',
 'chevrolet cavalier',
 'chevrolet cavalier 2-door'

In [ ]:
import datetime as dt
import time as t

In [ ]:
print(t.time())

1606753267.2124684


In [ ]:
dtnow = dt.datetime.fromtimestamp(t.time())
dtnow

datetime.datetime(2020, 11, 30, 16, 22, 38, 545832)

In [ ]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour,dtnow.minute,dtnow.second

(2020, 11, 30, 16, 22, 38)

In [ ]:
delta = dt.timedelta(days=100)
delta

datetime.timedelta(100)

In [ ]:
today = dt.date.today()

In [ ]:
today-delta

datetime.date(2020, 8, 22)

In [ ]:
today>today-delta

True

In [ ]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda person: person.split()[0] + ' ' + person.split()[-1])(person))

#option 2
#list(map(split_title_and_name, people)) == list(map(???))


True
True
True
True


In [ ]:
import numpy as np

a = [1,2,3]
b = np.array(a)
print(b)
print(b.ndim)

[1 2 3]
1


In [ ]:
c = np.arange(0,30,2)
c

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
d = np.array([[1,2,3],[4,5,6]])
d.shape

(2, 3)

In [ ]:
c.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [ ]:
e = np.linspace(0,4,9)
e

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
e.resize(3,3)
e

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.diag(a)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
p = np.ones((2,3),int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.vstack((p,2*p))

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.hstack((p,2*p))

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [ ]:
h = np.array([4,5,6])
i = np.array([1,2,3])
h+i

array([5, 7, 9])

In [ ]:
h*i

array([ 4, 10, 18])

In [ ]:
h**2

array([16, 25, 36])

In [ ]:
h.dot(i)

32

In [ ]:
z = np.array([h,h*2])
z

array([[ 4,  5,  6],
       [ 8, 10, 12]])

In [ ]:
z.shape

(2, 3)

In [ ]:
z.T

array([[ 4,  8],
       [ 5, 10],
       [ 6, 12]])

In [ ]:
z.T.shape

(3, 2)

In [ ]:
z.dtype

dtype('int64')

In [ ]:
z = z.astype('f')
z.dtype

dtype('float32')

In [ ]:
z.max()

12.0

In [ ]:
z.min()

4.0

In [ ]:
z.sum()

45.0

In [ ]:
z.mean()

7.5

In [ ]:
z.std()

2.813657

In [ ]:
z.argmax()

5

In [ ]:
z.argmin()

0

In [ ]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [ ]:
s[-4:]

array([ 81, 100, 121, 144])

In [ ]:
s[-5::-1]

array([64, 49, 36, 25, 16,  9,  4,  1,  0])

In [ ]:
r = np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
r[2,2]

14

In [ ]:
r[-1,::2]

array([30, 32, 34])

In [ ]:
r[r>30]

array([31, 32, 33, 34, 35])

In [ ]:
r[r>30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [ ]:
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [ ]:
r2[:] = 0
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [ ]:
r_copy = r.copy()
r_copy[:] = 10

print(r_copy)
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [ ]:
ran = np.random.randint(0,10,(5,3))
ran

array([[4, 9, 6],
       [8, 5, 4],
       [8, 9, 3],
       [3, 0, 7],
       [5, 8, 9]])

In [ ]:
for row in ran:
  print(row)

[4 9 6]
[8 5 4]
[8 9 3]
[3 0 7]
[5 8 9]


In [ ]:
for i,row in enumerate(ran):
  print("row",i,"is",row)

row 0 is [4 9 6]
row 1 is [8 5 4]
row 2 is [8 9 3]
row 3 is [3 0 7]
row 4 is [5 8 9]


In [ ]:
ran2 = ran**2
ran2

array([[16, 81, 36],
       [64, 25, 16],
       [64, 81,  9],
       [ 9,  0, 49],
       [25, 64, 81]])

In [ ]:
for i,j in zip(ran,ran2):
  print(i,"+",j,"=",i+j)

[4 9 6] + [16 81 36] = [20 90 42]
[8 5 4] + [64 25 16] = [72 30 20]
[8 9 3] + [64 81  9] = [72 90 12]
[3 0 7] + [ 9  0 49] = [12  0 56]
[5 8 9] + [25 64 81] = [30 72 90]


In [ ]:
graduate_admission = np.genfromtxt('Admission_Predict.csv', dtype = None,delimiter=',',skip_header=1,
                                   names=('Serial No.','GRE Score','TOEFL Score','University Rating','SOP','LOR','CGPA','Research','Chance of Admit'))
graduate_admission

array([(  1, 337, 118, 4, 4.5, 4.5, 9.65, 1, 0.92),
       (  2, 324, 107, 4, 4. , 4.5, 8.87, 1, 0.76),
       (  3, 316, 104, 3, 3. , 3.5, 8.  , 1, 0.72),
       (  4, 322, 110, 3, 3.5, 2.5, 8.67, 1, 0.8 ),
       (  5, 314, 103, 2, 2. , 3. , 8.21, 0, 0.65),
       (  6, 330, 115, 5, 4.5, 3. , 9.34, 1, 0.9 ),
       (  7, 321, 109, 3, 3. , 4. , 8.2 , 1, 0.75),
       (  8, 308, 101, 2, 3. , 4. , 7.9 , 0, 0.68),
       (  9, 302, 102, 1, 2. , 1.5, 8.  , 0, 0.5 ),
       ( 10, 323, 108, 3, 3.5, 3. , 8.6 , 0, 0.45),
       ( 11, 325, 106, 3, 3.5, 4. , 8.4 , 1, 0.52),
       ( 12, 327, 111, 4, 4. , 4.5, 9.  , 1, 0.84),
       ( 13, 328, 112, 4, 4. , 4.5, 9.1 , 1, 0.78),
       ( 14, 307, 109, 3, 4. , 3. , 8.  , 1, 0.62),
       ( 15, 311, 104, 3, 3.5, 2. , 8.2 , 1, 0.61),
       ( 16, 314, 105, 3, 3.5, 2.5, 8.3 , 0, 0.54),
       ( 17, 317, 107, 3, 4. , 3. , 8.7 , 0, 0.66),
       ( 18, 319, 106, 3, 4. , 3. , 8.  , 1, 0.65),
       ( 19, 318, 110, 3, 4. , 3. , 8.8 , 0, 0.63),
       ( 20,

In [ ]:
graduate_admission.shape

(400,)

In [ ]:
graduate_admission['CGPA'][0:5]

array([9.65, 8.87, 8.  , 8.67, 8.21])

In [ ]:
graduate_admission['CGPA'] = graduate_admission['CGPA']/10*4

In [ ]:
graduate_admission['CGPA'][0:20]

array([3.86 , 3.548, 3.2  , 3.468, 3.284, 3.736, 3.28 , 3.16 , 3.2  ,
       3.44 , 3.36 , 3.6  , 3.64 , 3.2  , 3.28 , 3.32 , 3.48 , 3.2  ,
       3.52 , 3.4  ])

In [ ]:
len(graduate_admission[graduate_admission['Research']==1])

219

In [ ]:
print(graduate_admission[graduate_admission['Chance_of_Admit']>0.8]['GRE_Score'].mean())

328.7350427350427


In [ ]:
print(graduate_admission[graduate_admission['Chance_of_Admit']<0.4]['GRE_Score'].mean())

302.2857142857143


In [ ]:
print(graduate_admission[graduate_admission['Chance_of_Admit']>0.8]['CGPA'].mean())
print(graduate_admission[graduate_admission['Chance_of_Admit']<0.4]['CGPA'].mean())

3.7106666666666666
3.0222857142857142


In [ ]:
import re

text = "My name is Mayank"
if re.search("Mayank",text):
  print("Correct ans")
else:
  print("Wrong ans")

Correct ans


In [ ]:
text = "Mayank is great. Competative coding is Mayank passion. Mayank learns fast"
re.split("Mayank",text)

['', ' is great. Competative coding is ', ' passion. ', ' learns fast']

In [ ]:
re.findall("Mayank",text)

['Mayank', 'Mayank', 'Mayank']

In [ ]:
re.search("^Mayank",text)

<_sre.SRE_Match object; span=(0, 6), match='Mayank'>

In [ ]:
text1 = "AABABCABC"
re.findall("B",text1)

['B', 'B', 'B']

In [ ]:
re.findall("[AB]",text1)

['A', 'A', 'B', 'A', 'B', 'A', 'B']

In [ ]:
re.findall("[A][B-C]",text1)

['AB', 'AB', 'AB']

In [ ]:
re.findall("[^A]",text1)

['B', 'B', 'C', 'B', 'C']

In [ ]:
re.findall("A{1,2}",text1) #no extra space in between

['AA', 'A', 'A']

In [ ]:
# with open("https://dl.packetstormsecurity.net/papers/legal/ferpa.txt","r") as file:
#   wiki = file.read()
import urllib
import requests
url = "https://dl.packetstormsecurity.net/papers/legal/ferpa.txt"
file = urllib.request.urlopen(url)

for i in file:
  decoded_line = i.decode("utf-8")
  print(decoded_line)

   ****************************************************************

   *   Document from the CPSR Privacy/Information Archive         *

   *  FTP/Gopher/WAIS: cpsr.org  email: listserv@cpsr.org "help"  *

   *                                                              *

   *    For more information contact: cpsr@csli.stanford.edu      *

   *                        415-322-3778                          *

   ****************************************************************







Family Educational Right to Privacy Act.  (Buckley Ammendment)



(as of 4/93)



20 USC  S. 1232g





S.  1232g.  Family educational and privacy rights



   (a) Conditions for availability of funds to educational agencies or

institutions; inspection and review of education records; specific

information to be made available; procedure for access to education

records; reasonableness of time for such access; hearings; written

explanations by parents; definitions.



   (1) (A) No funds shall be made av

In [ ]:
import pandas as pd

name = ["Mayank","Harsh","Shashank"]
pd.Series(name)

0      Mayank
1       Harsh
2    Shashank
dtype: object

In [ ]:
numbers = [1,2,3,4,5]
pd.Series(numbers)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
numbers = [1,2,None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [ ]:
import numpy as np
np.nan == None

False

In [ ]:
np.nan == np.nan

False

In [ ]:
np.isnan(np.nan)

True

In [1]:
import pandas as pd

scores = {"Mayank":"Maths",
          "Harsh":"Chemistry",
          "Shashank":"Physics"}

new = pd.Series(scores)
print(new)

Mayank          Maths
Harsh       Chemistry
Shashank      Physics
dtype: object


In [2]:
new.index

Index(['Mayank', 'Harsh', 'Shashank'], dtype='object')

In [3]:
scores = [("Mayank","Parashar"),("Harsh","Neel")]

pd.Series(scores)
scores

[('Mayank', 'Parashar'), ('Harsh', 'Neel')]

In [4]:
new = pd.Series(["mayank","harsh","shanki"],index=["math","phy","chem"])
new

math    mayank
phy      harsh
chem    shanki
dtype: object

In [6]:
import pandas as pd

scores = {"Mayank":"Maths",
          "Harsh":"Chemistry",
          "Shashank":"Physics"}

new = pd.Series(scores)
print(new.iloc[2])
print(new.loc['Harsh'])

Physics
Chemistry


In [8]:
import numpy as np
import pandas as pd
new = pd.Series(np.random.randint(0,1000,10000))
new.head()

0    637
1    375
2    261
3    965
4    907
dtype: int64

In [9]:
len(new)

10000

In [10]:
%%timeit -n 100
total = 0
for number in new:
  total += number

total/len(new)

100 loops, best of 3: 1.32 ms per loop


In [15]:
%%timeit -n 100
total = np.sum(new)
total/len(new)

100 loops, best of 3: 86.2 µs per loop


In [16]:
new.head()

0    637
1    375
2    261
3    965
4    907
dtype: int64

In [17]:
new+=2
new.head()

0    639
1    377
2    263
3    967
4    909
dtype: int64

In [24]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
for label,value in s.iteritems():
  s.loc[label]=value+2

10 loops, best of 3: 624 ms per loop


In [25]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
s+=2

10 loops, best of 3: 445 µs per loop


In [26]:
s = pd.Series([1,2,3])
s.loc["mayank"] = 100
s

0           1
1           2
2           3
mayank    100
dtype: int64

In [28]:
import pandas as pd
record1 = pd.Series({"Name":"Mayank",
                     "Class":"Maths",
                     "Grade":80})
record2 = pd.Series({"Name":"Harsh",
                     "Class":"Physics",
                     "Grade":85})
record3 = pd.Series({"Name":"Shanki",
                     "Class":"Chem",
                     "Grade":90})
df = pd.DataFrame([record1,record2,record3],index=[1,2,3])
df

Name    Class  Grade
1  Mayank    Maths     80
2   Harsh  Physics     85
3  Shanki     Chem     90

In [30]:
students = [{"Name":"Mayank","Class":"Maths","Grade":80},{"Name":"Shanki","Class":"Chem","Grade":85},{"Name":"Pranav","Class":"Phy","Grade":95}]
df = pd.DataFrame(students,index=["School_1","School_2","School_3"])
df

Name  Class  Grade
School_1  Mayank  Maths     80
School_2  Shanki   Chem     85
School_3  Pranav    Phy     95

In [31]:
df.loc['School_1']

Name     Mayank
Class     Maths
Grade        80
Name: School_1, dtype: object

In [33]:
type(df.loc["School_1"])

pandas.core.series.Series

In [34]:
df.loc['School_1','Name']

'Mayank'

In [35]:
df.T

School_1 School_2 School_3
Name    Mayank   Shanki   Pranav
Class    Maths     Chem      Phy
Grade       80       85       95

In [37]:
df.T.loc['Name']

School_1    Mayank
School_2    Shanki
School_3    Pranav
Name: Name, dtype: object

In [39]:
df['Class']

School_1    Maths
School_2     Chem
School_3      Phy
Name: Class, dtype: object

In [41]:
df.loc['School_1']['Name']

'Mayank'

In [43]:
df.loc[:,['Name','Grade']]

Name  Grade
School_1  Mayank     80
School_2  Shanki     85
School_3  Pranav     95

In [45]:
df.drop('School_1') #remove row and display copy of df

Name Class  Grade
School_2  Shanki  Chem     85
School_3  Pranav   Phy     95

In [46]:
df

Name  Class  Grade
School_1  Mayank  Maths     80
School_2  Shanki   Chem     85
School_3  Pranav    Phy     95

In [47]:
copy_df = df.copy()
copy_df.drop("Name",inplace=True,axis=1)
copy_df

Class  Grade
School_1  Maths     80
School_2   Chem     85
School_3    Phy     95

In [48]:
del copy_df['Class']
copy_df

Grade
School_1     80
School_2     85
School_3     95

In [49]:
df["Ranking"] = None
df

Name  Class  Grade Ranking
School_1  Mayank  Maths     80    None
School_2  Shanki   Chem     85    None
School_3  Pranav    Phy     95    None