<a href="https://colab.research.google.com/github/mayankp158/Michigan-University-ML-/blob/main/python_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import csv
%precision 2
with open('mpg.csv') as new:
  mpg = list(csv.DictReader(new))

mpg[:3]

[OrderedDict([('mpg', '18'),
              ('cylinders', '8'),
              ('displacement', '307'),
              ('horsepower', '130'),
              ('weight', '3504'),
              ('acceleration', '12'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'chevrolet chevelle malibu')]),
 OrderedDict([('mpg', '15'),
              ('cylinders', '8'),
              ('displacement', '350'),
              ('horsepower', '165'),
              ('weight', '3693'),
              ('acceleration', '11.5'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'buick skylark 320')]),
 OrderedDict([('mpg', '18'),
              ('cylinders', '8'),
              ('displacement', '318'),
              ('horsepower', '150'),
              ('weight', '3436'),
              ('acceleration', '11'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'plymouth satellite')])]

In [ ]:
len(mpg)

398

In [ ]:
mpg[0].keys()

odict_keys(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'name'])

In [ ]:
sum(float(i['weight']) for i in mpg)/len(mpg)

2970.42

In [ ]:
cyl = set(j['cylinders'] for j in mpg)
cyl

{'3', '4', '5', '6', '8'}

In [ ]:
ctympgbycl = []
for i in cyl:
  sum1 = 0
  count1 = 0
  for j in mpg:
    if j['cylinders'] == i:
      sum1 += float(j['cylinders'])
      count1 += 1
  ctympgbycl.append((i,sum1/count1))

ctympgbycl.sort(key=lambda x: x[0])
ctympgbycl

[('3', 3.00), ('4', 4.00), ('5', 5.00), ('6', 6.00), ('8', 8.00)]

In [ ]:
vc = set(j['name'] for j in mpg)
vc

{'amc ambassador brougham',
 'amc ambassador dpl',
 'amc ambassador sst',
 'amc concord',
 'amc concord d/l',
 'amc concord dl',
 'amc concord dl 6',
 'amc gremlin',
 'amc hornet',
 'amc hornet sportabout (sw)',
 'amc matador',
 'amc matador (sw)',
 'amc pacer',
 'amc pacer d/l',
 'amc rebel sst',
 'amc spirit dl',
 'audi 100 ls',
 'audi 100ls',
 'audi 4000',
 'audi 5000',
 'audi 5000s (diesel)',
 'audi fox',
 'bmw 2002',
 'bmw 320i',
 'buick century',
 'buick century 350',
 'buick century limited',
 'buick century luxus (sw)',
 'buick century special',
 'buick electra 225 custom',
 'buick estate wagon (sw)',
 'buick lesabre custom',
 'buick opel isuzu deluxe',
 'buick regal sport coupe (turbo)',
 'buick skyhawk',
 'buick skylark',
 'buick skylark 320',
 'buick skylark limited',
 'cadillac eldorado',
 'cadillac seville',
 'capri ii',
 'chevroelt chevelle malibu',
 'chevrolet bel air',
 'chevrolet camaro',
 'chevrolet caprice classic',
 'chevrolet cavalier',
 'chevrolet cavalier 2-door'

In [ ]:
import datetime as dt
import time as t

In [ ]:
print(t.time())

1606753267.2124684


In [ ]:
dtnow = dt.datetime.fromtimestamp(t.time())
dtnow

datetime.datetime(2020, 11, 30, 16, 22, 38, 545832)

In [ ]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour,dtnow.minute,dtnow.second

(2020, 11, 30, 16, 22, 38)

In [ ]:
delta = dt.timedelta(days=100)
delta

datetime.timedelta(100)

In [ ]:
today = dt.date.today()

In [ ]:
today-delta

datetime.date(2020, 8, 22)

In [ ]:
today>today-delta

True

In [ ]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda person: person.split()[0] + ' ' + person.split()[-1])(person))

#option 2
#list(map(split_title_and_name, people)) == list(map(???))


True
True
True
True


In [ ]:
import numpy as np

a = [1,2,3]
b = np.array(a)
print(b)
print(b.ndim)

[1 2 3]
1


In [ ]:
c = np.arange(0,30,2)
c

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
d = np.array([[1,2,3],[4,5,6]])
d.shape

(2, 3)

In [ ]:
c.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [ ]:
e = np.linspace(0,4,9)
e

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
e.resize(3,3)
e

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.diag(a)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
p = np.ones((2,3),int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.vstack((p,2*p))

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.hstack((p,2*p))

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [ ]:
h = np.array([4,5,6])
i = np.array([1,2,3])
h+i

array([5, 7, 9])

In [ ]:
h*i

array([ 4, 10, 18])

In [ ]:
h**2

array([16, 25, 36])

In [ ]:
h.dot(i)

32

In [ ]:
z = np.array([h,h*2])
z

array([[ 4,  5,  6],
       [ 8, 10, 12]])

In [ ]:
z.shape

(2, 3)

In [ ]:
z.T

array([[ 4,  8],
       [ 5, 10],
       [ 6, 12]])

In [ ]:
z.T.shape

(3, 2)

In [ ]:
z.dtype

dtype('int64')

In [ ]:
z = z.astype('f')
z.dtype

dtype('float32')

In [ ]:
z.max()

12.0

In [ ]:
z.min()

4.0

In [ ]:
z.sum()

45.0

In [ ]:
z.mean()

7.5

In [ ]:
z.std()

2.813657

In [ ]:
z.argmax()

5

In [ ]:
z.argmin()

0

In [ ]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [ ]:
s[-4:]

array([ 81, 100, 121, 144])

In [ ]:
s[-5::-1]

array([64, 49, 36, 25, 16,  9,  4,  1,  0])

In [ ]:
r = np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
r[2,2]

14

In [ ]:
r[-1,::2]

array([30, 32, 34])

In [ ]:
r[r>30]

array([31, 32, 33, 34, 35])

In [ ]:
r[r>30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [ ]:
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [ ]:
r2[:] = 0
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [ ]:
r_copy = r.copy()
r_copy[:] = 10

print(r_copy)
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [ ]:
ran = np.random.randint(0,10,(5,3))
ran

array([[4, 9, 6],
       [8, 5, 4],
       [8, 9, 3],
       [3, 0, 7],
       [5, 8, 9]])

In [ ]:
for row in ran:
  print(row)

[4 9 6]
[8 5 4]
[8 9 3]
[3 0 7]
[5 8 9]


In [ ]:
for i,row in enumerate(ran):
  print("row",i,"is",row)

row 0 is [4 9 6]
row 1 is [8 5 4]
row 2 is [8 9 3]
row 3 is [3 0 7]
row 4 is [5 8 9]


In [ ]:
ran2 = ran**2
ran2

array([[16, 81, 36],
       [64, 25, 16],
       [64, 81,  9],
       [ 9,  0, 49],
       [25, 64, 81]])

In [ ]:
for i,j in zip(ran,ran2):
  print(i,"+",j,"=",i+j)

[4 9 6] + [16 81 36] = [20 90 42]
[8 5 4] + [64 25 16] = [72 30 20]
[8 9 3] + [64 81  9] = [72 90 12]
[3 0 7] + [ 9  0 49] = [12  0 56]
[5 8 9] + [25 64 81] = [30 72 90]


In [ ]:
graduate_admission = np.genfromtxt('Admission_Predict.csv', dtype = None,delimiter=',',skip_header=1,
                                   names=('Serial No.','GRE Score','TOEFL Score','University Rating','SOP','LOR','CGPA','Research','Chance of Admit'))
graduate_admission

array([(  1, 337, 118, 4, 4.5, 4.5, 9.65, 1, 0.92),
       (  2, 324, 107, 4, 4. , 4.5, 8.87, 1, 0.76),
       (  3, 316, 104, 3, 3. , 3.5, 8.  , 1, 0.72),
       (  4, 322, 110, 3, 3.5, 2.5, 8.67, 1, 0.8 ),
       (  5, 314, 103, 2, 2. , 3. , 8.21, 0, 0.65),
       (  6, 330, 115, 5, 4.5, 3. , 9.34, 1, 0.9 ),
       (  7, 321, 109, 3, 3. , 4. , 8.2 , 1, 0.75),
       (  8, 308, 101, 2, 3. , 4. , 7.9 , 0, 0.68),
       (  9, 302, 102, 1, 2. , 1.5, 8.  , 0, 0.5 ),
       ( 10, 323, 108, 3, 3.5, 3. , 8.6 , 0, 0.45),
       ( 11, 325, 106, 3, 3.5, 4. , 8.4 , 1, 0.52),
       ( 12, 327, 111, 4, 4. , 4.5, 9.  , 1, 0.84),
       ( 13, 328, 112, 4, 4. , 4.5, 9.1 , 1, 0.78),
       ( 14, 307, 109, 3, 4. , 3. , 8.  , 1, 0.62),
       ( 15, 311, 104, 3, 3.5, 2. , 8.2 , 1, 0.61),
       ( 16, 314, 105, 3, 3.5, 2.5, 8.3 , 0, 0.54),
       ( 17, 317, 107, 3, 4. , 3. , 8.7 , 0, 0.66),
       ( 18, 319, 106, 3, 4. , 3. , 8.  , 1, 0.65),
       ( 19, 318, 110, 3, 4. , 3. , 8.8 , 0, 0.63),
       ( 20,

In [ ]:
graduate_admission.shape

(400,)

In [ ]:
graduate_admission['CGPA'][0:5]

array([9.65, 8.87, 8.  , 8.67, 8.21])

In [ ]:
graduate_admission['CGPA'] = graduate_admission['CGPA']/10*4

In [ ]:
graduate_admission['CGPA'][0:20]

array([3.86 , 3.548, 3.2  , 3.468, 3.284, 3.736, 3.28 , 3.16 , 3.2  ,
       3.44 , 3.36 , 3.6  , 3.64 , 3.2  , 3.28 , 3.32 , 3.48 , 3.2  ,
       3.52 , 3.4  ])

In [ ]:
len(graduate_admission[graduate_admission['Research']==1])

219

In [ ]:
print(graduate_admission[graduate_admission['Chance_of_Admit']>0.8]['GRE_Score'].mean())

328.7350427350427


In [ ]:
print(graduate_admission[graduate_admission['Chance_of_Admit']<0.4]['GRE_Score'].mean())

302.2857142857143


In [ ]:
print(graduate_admission[graduate_admission['Chance_of_Admit']>0.8]['CGPA'].mean())
print(graduate_admission[graduate_admission['Chance_of_Admit']<0.4]['CGPA'].mean())

3.7106666666666666
3.0222857142857142


In [ ]:
import re

text = "My name is Mayank"
if re.search("Mayank",text):
  print("Correct ans")
else:
  print("Wrong ans")

Correct ans


In [ ]:
text = "Mayank is great. Competative coding is Mayank passion. Mayank learns fast"
re.split("Mayank",text)

['', ' is great. Competative coding is ', ' passion. ', ' learns fast']

In [ ]:
re.findall("Mayank",text)

['Mayank', 'Mayank', 'Mayank']

In [ ]:
re.search("^Mayank",text)

<_sre.SRE_Match object; span=(0, 6), match='Mayank'>

In [ ]:
text1 = "AABABCABC"
re.findall("B",text1)

['B', 'B', 'B']

In [ ]:
re.findall("[AB]",text1)

['A', 'A', 'B', 'A', 'B', 'A', 'B']

In [ ]:
re.findall("[A][B-C]",text1)

['AB', 'AB', 'AB']

In [ ]:
re.findall("[^A]",text1)

['B', 'B', 'C', 'B', 'C']

In [ ]:
re.findall("A{1,2}",text1) #no extra space in between

['AA', 'A', 'A']

In [ ]:
# with open("https://dl.packetstormsecurity.net/papers/legal/ferpa.txt","r") as file:
#   wiki = file.read()
import urllib
import requests
url = "https://dl.packetstormsecurity.net/papers/legal/ferpa.txt"
file = urllib.request.urlopen(url)

for i in file:
  decoded_line = i.decode("utf-8")
  print(decoded_line)

   ****************************************************************

   *   Document from the CPSR Privacy/Information Archive         *

   *  FTP/Gopher/WAIS: cpsr.org  email: listserv@cpsr.org "help"  *

   *                                                              *

   *    For more information contact: cpsr@csli.stanford.edu      *

   *                        415-322-3778                          *

   ****************************************************************







Family Educational Right to Privacy Act.  (Buckley Ammendment)



(as of 4/93)



20 USC  S. 1232g





S.  1232g.  Family educational and privacy rights



   (a) Conditions for availability of funds to educational agencies or

institutions; inspection and review of education records; specific

information to be made available; procedure for access to education

records; reasonableness of time for such access; hearings; written

explanations by parents; definitions.



   (1) (A) No funds shall be made av

In [ ]:
import pandas as pd

name = ["Mayank","Harsh","Shashank"]
pd.Series(name)

0      Mayank
1       Harsh
2    Shashank
dtype: object

In [ ]:
numbers = [1,2,3,4,5]
pd.Series(numbers)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
numbers = [1,2,None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [ ]:
import numpy as np
np.nan == None

False

In [ ]:
np.nan == np.nan

False

In [ ]:
np.isnan(np.nan)

True

In [1]:
import pandas as pd

scores = {"Mayank":"Maths",
          "Harsh":"Chemistry",
          "Shashank":"Physics"}

new = pd.Series(scores)
print(new)

Mayank          Maths
Harsh       Chemistry
Shashank      Physics
dtype: object


In [2]:
new.index

Index(['Mayank', 'Harsh', 'Shashank'], dtype='object')

In [3]:
scores = [("Mayank","Parashar"),("Harsh","Neel")]

pd.Series(scores)
scores

[('Mayank', 'Parashar'), ('Harsh', 'Neel')]

In [4]:
new = pd.Series(["mayank","harsh","shanki"],index=["math","phy","chem"])
new

math    mayank
phy      harsh
chem    shanki
dtype: object

In [6]:
import pandas as pd

scores = {"Mayank":"Maths",
          "Harsh":"Chemistry",
          "Shashank":"Physics"}

new = pd.Series(scores)
print(new.iloc[2])
print(new.loc['Harsh'])

Physics
Chemistry


In [8]:
import numpy as np
import pandas as pd
new = pd.Series(np.random.randint(0,1000,10000))
new.head()

0    637
1    375
2    261
3    965
4    907
dtype: int64

In [9]:
len(new)

10000

In [10]:
%%timeit -n 100
total = 0
for number in new:
  total += number

total/len(new)

100 loops, best of 3: 1.32 ms per loop


In [15]:
%%timeit -n 100
total = np.sum(new)
total/len(new)

100 loops, best of 3: 86.2 µs per loop


In [16]:
new.head()

0    637
1    375
2    261
3    965
4    907
dtype: int64

In [17]:
new+=2
new.head()

0    639
1    377
2    263
3    967
4    909
dtype: int64

In [24]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
for label,value in s.iteritems():
  s.loc[label]=value+2

10 loops, best of 3: 624 ms per loop


In [25]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
s+=2

10 loops, best of 3: 445 µs per loop


In [26]:
s = pd.Series([1,2,3])
s.loc["mayank"] = 100
s

0           1
1           2
2           3
mayank    100
dtype: int64

In [28]:
import pandas as pd
record1 = pd.Series({"Name":"Mayank",
                     "Class":"Maths",
                     "Grade":80})
record2 = pd.Series({"Name":"Harsh",
                     "Class":"Physics",
                     "Grade":85})
record3 = pd.Series({"Name":"Shanki",
                     "Class":"Chem",
                     "Grade":90})
df = pd.DataFrame([record1,record2,record3],index=[1,2,3])
df

Name    Class  Grade
1  Mayank    Maths     80
2   Harsh  Physics     85
3  Shanki     Chem     90

In [30]:
students = [{"Name":"Mayank","Class":"Maths","Grade":80},{"Name":"Shanki","Class":"Chem","Grade":85},{"Name":"Pranav","Class":"Phy","Grade":95}]
df = pd.DataFrame(students,index=["School_1","School_2","School_3"])
df

Name  Class  Grade
School_1  Mayank  Maths     80
School_2  Shanki   Chem     85
School_3  Pranav    Phy     95

In [31]:
df.loc['School_1']

Name     Mayank
Class     Maths
Grade        80
Name: School_1, dtype: object

In [33]:
type(df.loc["School_1"])

pandas.core.series.Series

In [34]:
df.loc['School_1','Name']

'Mayank'

In [35]:
df.T

School_1 School_2 School_3
Name    Mayank   Shanki   Pranav
Class    Maths     Chem      Phy
Grade       80       85       95

In [37]:
df.T.loc['Name']

School_1    Mayank
School_2    Shanki
School_3    Pranav
Name: Name, dtype: object

In [39]:
df['Class']

School_1    Maths
School_2     Chem
School_3      Phy
Name: Class, dtype: object

In [41]:
df.loc['School_1']['Name']

'Mayank'

In [43]:
df.loc[:,['Name','Grade']]

Name  Grade
School_1  Mayank     80
School_2  Shanki     85
School_3  Pranav     95

In [45]:
df.drop('School_1') #remove row and display copy of df

Name Class  Grade
School_2  Shanki  Chem     85
School_3  Pranav   Phy     95

In [46]:
df

Name  Class  Grade
School_1  Mayank  Maths     80
School_2  Shanki   Chem     85
School_3  Pranav    Phy     95

In [47]:
copy_df = df.copy()
copy_df.drop("Name",inplace=True,axis=1)
copy_df

Class  Grade
School_1  Maths     80
School_2   Chem     85
School_3    Phy     95

In [48]:
del copy_df['Class']
copy_df

Grade
School_1     80
School_2     85
School_3     95

In [49]:
df["Ranking"] = None
df

Name  Class  Grade Ranking
School_1  Mayank  Maths     80    None
School_2  Shanki   Chem     85    None
School_3  Pranav    Phy     95    None

In [3]:
!cat /Admission_Predict.csv

Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR ,CGPA,Research,Chance of Admit 
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4,4.5,8.87,1,0.76
3,316,104,3,3,3.5,8,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.8
5,314,103,2,2,3,8.21,0,0.65
6,330,115,5,4.5,3,9.34,1,0.9
7,321,109,3,3,4,8.2,1,0.75
8,308,101,2,3,4,7.9,0,0.68
9,302,102,1,2,1.5,8,0,0.5
10,323,108,3,3.5,3,8.6,0,0.45
11,325,106,3,3.5,4,8.4,1,0.52
12,327,111,4,4,4.5,9,1,0.84
13,328,112,4,4,4.5,9.1,1,0.78
14,307,109,3,4,3,8,1,0.62
15,311,104,3,3.5,2,8.2,1,0.61
16,314,105,3,3.5,2.5,8.3,0,0.54
17,317,107,3,4,3,8.7,0,0.66
18,319,106,3,4,3,8,1,0.65
19,318,110,3,4,3,8.8,0,0.63
20,303,102,3,3.5,3,8.5,0,0.62
21,312,107,3,3,2,7.9,1,0.64
22,325,114,4,3,2,8.4,0,0.7
23,328,116,5,5,5,9.5,1,0.94
24,334,119,5,5,4.5,9.7,1,0.95
25,336,119,5,4,3.5,9.8,1,0.97
26,340,120,5,4.5,4.5,9.6,1,0.94
27,322,109,5,4.5,3.5,8.8,0,0.76
28,298,98,2,1.5,2.5,7.5,1,0.44
29,295,93,1,2,2,7.2,0,0.46
30,310,99,2,1.5,2,7.3,0,0.54
31,300,97,2,3,3,8.1,1,0.65
32,327,103,3,

In [4]:
import pandas as pd
df = pd.read_csv('/Admission_Predict.csv')
df.head()

Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit 
0           1        337          118  ...  9.65         1              0.92
1           2        324          107  ...  8.87         1              0.76
2           3        316          104  ...  8.00         1              0.72
3           4        322          110  ...  8.67         1              0.80
4           5        314          103  ...  8.21         0              0.65

[5 rows x 9 columns]

In [5]:
import pandas as pd
df = pd.read_csv('/Admission_Predict.csv',index_col=0)
df.head()

GRE Score  TOEFL Score  ...  Research  Chance of Admit 
Serial No.                          ...                            
1                 337          118  ...         1              0.92
2                 324          107  ...         1              0.76
3                 316          104  ...         1              0.72
4                 322          110  ...         1              0.80
5                 314          103  ...         0              0.65

[5 rows x 8 columns]

In [25]:
import pandas as pd
df = pd.read_csv('/Admission_Predict.csv',index_col=0)
new_df = df.rename(columns={'SOP':'Statement of Purpose'})
new_df.head()

GRE Score  TOEFL Score  ...  Research  Chance of Admit 
Serial No.                          ...                            
1                 337          118  ...         1              0.92
2                 324          107  ...         1              0.76
3                 316          104  ...         1              0.72
4                 322          110  ...         1              0.80
5                 314          103  ...         0              0.65

[5 rows x 8 columns]

In [26]:
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit '],
      dtype='object')

In [28]:
new_df = new_df.rename(mapper=str.strip,axis='columns')
new_df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'Statement of Purpose',
       'LOR', 'CGPA', 'Research', 'Chance of Admit'],
      dtype='object')

In [29]:
new_df = new_df.rename(columns={'LOR':'Letter of Recommendation'})
new_df.head()

GRE Score  TOEFL Score  ...  Research  Chance of Admit
Serial No.                          ...                           
1                 337          118  ...         1             0.92
2                 324          107  ...         1             0.76
3                 316          104  ...         1             0.72
4                 322          110  ...         1             0.80
5                 314          103  ...         0             0.65

[5 rows x 8 columns]

In [30]:
cols = list(new_df.columns)
cols = [i.lower() for i in cols]
cols

['gre score',
 'toefl score',
 'university rating',
 'statement of purpose',
 'letter of recommendation',
 'cgpa',
 'research',
 'chance of admit']

In [31]:
new_df.columns = cols
new_df.head()

gre score  toefl score  ...  research  chance of admit
Serial No.                          ...                           
1                 337          118  ...         1             0.92
2                 324          107  ...         1             0.76
3                 316          104  ...         1             0.72
4                 322          110  ...         1             0.80
5                 314          103  ...         0             0.65

[5 rows x 8 columns]

In [35]:
import pandas as pd
df = pd.read_csv("/Admission_Predict.csv",index_col=0)
df.columns = [i.lower().strip() for i in df.columns]
df.head()

gre score  toefl score  ...  research  chance of admit
Serial No.                          ...                           
1                 337          118  ...         1             0.92
2                 324          107  ...         1             0.76
3                 316          104  ...         1             0.72
4                 322          110  ...         1             0.80
5                 314          103  ...         0             0.65

[5 rows x 8 columns]

In [36]:
mask = df['chance of admit']>0.7
mask

Serial No.
1       True
2       True
3       True
4       True
5      False
       ...  
396     True
397     True
398     True
399    False
400     True
Name: chance of admit, Length: 400, dtype: bool

In [37]:
df.where(mask).head()

gre score  toefl score  ...  research  chance of admit
Serial No.                          ...                           
1               337.0        118.0  ...       1.0             0.92
2               324.0        107.0  ...       1.0             0.76
3               316.0        104.0  ...       1.0             0.72
4               322.0        110.0  ...       1.0             0.80
5                 NaN          NaN  ...       NaN              NaN

[5 rows x 8 columns]

In [39]:
df.where(mask).dropna().head()

gre score  toefl score  ...  research  chance of admit
Serial No.                          ...                           
1               337.0        118.0  ...       1.0             0.92
2               324.0        107.0  ...       1.0             0.76
3               316.0        104.0  ...       1.0             0.72
4               322.0        110.0  ...       1.0             0.80
6               330.0        115.0  ...       1.0             0.90

[5 rows x 8 columns]

In [40]:
df[df['chance of admit']>0.7].head() #dropna and masking combined in single command

gre score  toefl score  ...  research  chance of admit
Serial No.                          ...                           
1                 337          118  ...         1             0.92
2                 324          107  ...         1             0.76
3                 316          104  ...         1             0.72
4                 322          110  ...         1             0.80
6                 330          115  ...         1             0.90

[5 rows x 8 columns]

In [43]:
df[['cgpa','toefl score']].head()

cgpa  toefl score
Serial No.                   
1           9.65          118
2           8.87          107
3           8.00          104
4           8.67          110
5           8.21          103

In [44]:
(df['chance of admit']>0.7) & (df['chance of admit']<0.9)

Serial No.
1      False
2       True
3       True
4       True
5      False
       ...  
396     True
397     True
398    False
399    False
400    False
Name: chance of admit, Length: 400, dtype: bool

In [45]:
df['chance of admit'].gt(0.7) & df['chance of admit'].lt(0.9)

Serial No.
1      False
2       True
3       True
4       True
5      False
       ...  
396     True
397     True
398    False
399    False
400    False
Name: chance of admit, Length: 400, dtype: bool

In [46]:
df['chance of admit'].gt(0.7).lt(0.9)

Serial No.
1      False
2      False
3      False
4      False
5       True
       ...  
396    False
397    False
398    False
399     True
400    False
Name: chance of admit, Length: 400, dtype: bool

In [48]:
import csv
with open('/Admission_Predict.csv') as new1:
  a = list(csv.DictReader(new1))
a

[OrderedDict([('Serial No.', '1'),
              ('GRE Score', '337'),
              ('TOEFL Score', '118'),
              ('University Rating', '4'),
              ('SOP', '4.5'),
              ('LOR ', '4.5'),
              ('CGPA', '9.65'),
              ('Research', '1'),
              ('Chance of Admit ', '0.92')]),
 OrderedDict([('Serial No.', '2'),
              ('GRE Score', '324'),
              ('TOEFL Score', '107'),
              ('University Rating', '4'),
              ('SOP', '4'),
              ('LOR ', '4.5'),
              ('CGPA', '8.87'),
              ('Research', '1'),
              ('Chance of Admit ', '0.76')]),
 OrderedDict([('Serial No.', '3'),
              ('GRE Score', '316'),
              ('TOEFL Score', '104'),
              ('University Rating', '3'),
              ('SOP', '3'),
              ('LOR ', '3.5'),
              ('CGPA', '8'),
              ('Research', '1'),
              ('Chance of Admit ', '0.72')]),
 OrderedDict([('Serial No.', '4'),
   

In [55]:
import numpy as np
a = np.genfromtxt('/Admission_Predict.csv',delimiter=',',names=('Serial No.','CGPA'),skip_header=1)
a

array([(  1., 337.), (  2., 324.), (  3., 316.), (  4., 322.),
       (  5., 314.), (  6., 330.), (  7., 321.), (  8., 308.),
       (  9., 302.), ( 10., 323.), ( 11., 325.), ( 12., 327.),
       ( 13., 328.), ( 14., 307.), ( 15., 311.), ( 16., 314.),
       ( 17., 317.), ( 18., 319.), ( 19., 318.), ( 20., 303.),
       ( 21., 312.), ( 22., 325.), ( 23., 328.), ( 24., 334.),
       ( 25., 336.), ( 26., 340.), ( 27., 322.), ( 28., 298.),
       ( 29., 295.), ( 30., 310.), ( 31., 300.), ( 32., 327.),
       ( 33., 338.), ( 34., 340.), ( 35., 331.), ( 36., 320.),
       ( 37., 299.), ( 38., 300.), ( 39., 304.), ( 40., 307.),
       ( 41., 308.), ( 42., 316.), ( 43., 313.), ( 44., 332.),
       ( 45., 326.), ( 46., 322.), ( 47., 329.), ( 48., 339.),
       ( 49., 321.), ( 50., 327.), ( 51., 313.), ( 52., 312.),
       ( 53., 334.), ( 54., 324.), ( 55., 322.), ( 56., 320.),
       ( 57., 316.), ( 58., 298.), ( 59., 300.), ( 60., 311.),
       ( 61., 309.), ( 62., 307.), ( 63., 304.), ( 64.,

In [57]:
import pandas as pd
df = pd.read_csv('/Admission_Predict.csv')
df

Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit 
0             1        337          118  ...  9.65         1              0.92
1             2        324          107  ...  8.87         1              0.76
2             3        316          104  ...  8.00         1              0.72
3             4        322          110  ...  8.67         1              0.80
4             5        314          103  ...  8.21         0              0.65
..          ...        ...          ...  ...   ...       ...               ...
395         396        324          110  ...  9.04         1              0.82
396         397        325          107  ...  9.11         1              0.84
397         398        330          116  ...  9.45         1              0.91
398         399        312          103  ...  8.78         0              0.67
399         400        333          117  ...  9.66         1              0.95

[400 rows x 9 columns]

In [60]:
import urllib
import requests
url = 'http://textfiles.com/adventure/aencounter.txt'
new = urllib.request.urlopen(url)

for i in new:
  decoded = i.decode('utf-8')
  print(decoded)

***************************************

*                                     *

*            HOW TO SOLVE:            *

*                                     *

*        THE ALPINE ENCOUNTER         *

*                                     *

***************************************



THIS ADVENTURE IS TRULY AN ENIGMA.

IT CAN BE SOLVED IN HUNDREDS OF MOVES

OR HALF A DOZEN....

WELL I HAVEN'T PLAYED THE HUNDRED MOVE

VERSION...SO HERE'S THE SHORT ONE.



COMMANDS IN BRACKETS:



 [N] THIS WILL PUT YOU INSIDE.

 [N] THIS WILL GET YOU NEAR THE DESK.

 [W] THIS WILL GET YOU TO THE REGIS-

     TRATION DESK.

 [REGISTER] A FORMALITY. FILL IN ANY

   NAME, ADDRESS, ETC.

 [WAIT] FOR A BLONDE WOMAN TO APPEAR.

   SHE'LL APPEAR AROUND 9:45.

   AT THAT POINT PRESS A KEY (NOT

   BEFORE.)

 [LOOK BACKPACK] THIS WILL UNCOVER A

   VASE.

 [TAKE VASE] YOU HAVE THE VITAL

   INFORMATION UNDER YOUR NOSE!

 [CALL INSPECTOR] YOU HAVE WON!



   THERE ARE MANY OTHER PLACES TO GO,

THINGS TO DO, E