<a href="https://colab.research.google.com/github/mayankp158/Michigan-University-ML-/blob/main/python_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import csv
%precision 2
with open('mpg.csv') as new:
  mpg = list(csv.DictReader(new))

mpg[:3]

[OrderedDict([('mpg', '18'),
              ('cylinders', '8'),
              ('displacement', '307'),
              ('horsepower', '130'),
              ('weight', '3504'),
              ('acceleration', '12'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'chevrolet chevelle malibu')]),
 OrderedDict([('mpg', '15'),
              ('cylinders', '8'),
              ('displacement', '350'),
              ('horsepower', '165'),
              ('weight', '3693'),
              ('acceleration', '11.5'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'buick skylark 320')]),
 OrderedDict([('mpg', '18'),
              ('cylinders', '8'),
              ('displacement', '318'),
              ('horsepower', '150'),
              ('weight', '3436'),
              ('acceleration', '11'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'plymouth satellite')])]

In [9]:
len(mpg)

398

In [10]:
mpg[0].keys()

odict_keys(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'name'])

In [14]:
sum(float(i['weight']) for i in mpg)/len(mpg)

2970.42

In [15]:
cyl = set(j['cylinders'] for j in mpg)
cyl

{'3', '4', '5', '6', '8'}

In [23]:
ctympgbycl = []
for i in cyl:
  sum1 = 0
  count1 = 0
  for j in mpg:
    if j['cylinders'] == i:
      sum1 += float(j['cylinders'])
      count1 += 1
  ctympgbycl.append((i,sum1/count1))

ctympgbycl.sort(key=lambda x: x[0])
ctympgbycl

[('3', 3.00), ('4', 4.00), ('5', 5.00), ('6', 6.00), ('8', 8.00)]

In [24]:
vc = set(j['name'] for j in mpg)
vc

{'amc ambassador brougham',
 'amc ambassador dpl',
 'amc ambassador sst',
 'amc concord',
 'amc concord d/l',
 'amc concord dl',
 'amc concord dl 6',
 'amc gremlin',
 'amc hornet',
 'amc hornet sportabout (sw)',
 'amc matador',
 'amc matador (sw)',
 'amc pacer',
 'amc pacer d/l',
 'amc rebel sst',
 'amc spirit dl',
 'audi 100 ls',
 'audi 100ls',
 'audi 4000',
 'audi 5000',
 'audi 5000s (diesel)',
 'audi fox',
 'bmw 2002',
 'bmw 320i',
 'buick century',
 'buick century 350',
 'buick century limited',
 'buick century luxus (sw)',
 'buick century special',
 'buick electra 225 custom',
 'buick estate wagon (sw)',
 'buick lesabre custom',
 'buick opel isuzu deluxe',
 'buick regal sport coupe (turbo)',
 'buick skyhawk',
 'buick skylark',
 'buick skylark 320',
 'buick skylark limited',
 'cadillac eldorado',
 'cadillac seville',
 'capri ii',
 'chevroelt chevelle malibu',
 'chevrolet bel air',
 'chevrolet camaro',
 'chevrolet caprice classic',
 'chevrolet cavalier',
 'chevrolet cavalier 2-door'

In [30]:
import datetime as dt
import time as t

In [31]:
print(t.time())

1606753267.2124684


In [33]:
dtnow = dt.datetime.fromtimestamp(t.time())
dtnow

datetime.datetime(2020, 11, 30, 16, 22, 38, 545832)

In [35]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour,dtnow.minute,dtnow.second

(2020, 11, 30, 16, 22, 38)

In [36]:
delta = dt.timedelta(days=100)
delta

datetime.timedelta(100)

In [39]:
today = dt.date.today()

In [40]:
today-delta

datetime.date(2020, 8, 22)

In [41]:
today>today-delta

True

In [43]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda person: person.split()[0] + ' ' + person.split()[-1])(person))

#option 2
#list(map(split_title_and_name, people)) == list(map(???))


True
True
True
True


In [89]:
import numpy as np

a = [1,2,3]
b = np.array(a)
print(b)
print(b.ndim)

[1 2 3]
1


In [5]:
c = np.arange(0,30,2)
c

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [9]:
d = np.array([[1,2,3],[4,5,6]])
d.shape

(2, 3)

In [11]:
c.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [12]:
e = np.linspace(0,4,9)
e

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [14]:
e.resize(3,3)
e

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.diag(a)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [25]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [26]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [31]:
p = np.ones((2,3),int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [33]:
np.vstack((p,2*p))

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [34]:
np.hstack((p,2*p))

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [44]:
h = np.array([4,5,6])
i = np.array([1,2,3])
h+i

array([5, 7, 9])

In [45]:
h*i

array([ 4, 10, 18])

In [46]:
h**2

array([16, 25, 36])

In [47]:
h.dot(i)

32

In [49]:
z = np.array([h,h*2])
z

array([[ 4,  5,  6],
       [ 8, 10, 12]])

In [51]:
z.shape

(2, 3)

In [52]:
z.T

array([[ 4,  8],
       [ 5, 10],
       [ 6, 12]])

In [53]:
z.T.shape

(3, 2)

In [54]:
z.dtype

dtype('int64')

In [56]:
z = z.astype('f')
z.dtype

dtype('float32')

In [57]:
z.max()

12.0

In [58]:
z.min()

4.0

In [59]:
z.sum()

45.0

In [60]:
z.mean()

7.5

In [62]:
z.std()

2.813657

In [63]:
z.argmax()

5

In [64]:
z.argmin()

0

In [66]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [67]:
s[-4:]

array([ 81, 100, 121, 144])

In [71]:
s[-5::-1]

array([64, 49, 36, 25, 16,  9,  4,  1,  0])

In [72]:
r = np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [73]:
r[2,2]

14

In [74]:
r[-1,::2]

array([30, 32, 34])

In [75]:
r[r>30]

array([31, 32, 33, 34, 35])

In [76]:
r[r>30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [77]:
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [78]:
r2[:] = 0
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [79]:
r_copy = r.copy()
r_copy[:] = 10

print(r_copy)
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [81]:
ran = np.random.randint(0,10,(5,3))
ran

array([[4, 9, 6],
       [8, 5, 4],
       [8, 9, 3],
       [3, 0, 7],
       [5, 8, 9]])

In [82]:
for row in ran:
  print(row)

[4 9 6]
[8 5 4]
[8 9 3]
[3 0 7]
[5 8 9]


In [84]:
for i,row in enumerate(ran):
  print("row",i,"is",row)

row 0 is [4 9 6]
row 1 is [8 5 4]
row 2 is [8 9 3]
row 3 is [3 0 7]
row 4 is [5 8 9]


In [86]:
ran2 = ran**2
ran2

array([[16, 81, 36],
       [64, 25, 16],
       [64, 81,  9],
       [ 9,  0, 49],
       [25, 64, 81]])

In [87]:
for i,j in zip(ran,ran2):
  print(i,"+",j,"=",i+j)

[4 9 6] + [16 81 36] = [20 90 42]
[8 5 4] + [64 25 16] = [72 30 20]
[8 9 3] + [64 81  9] = [72 90 12]
[3 0 7] + [ 9  0 49] = [12  0 56]
[5 8 9] + [25 64 81] = [30 72 90]
